### ISSUE TITLE
Unable to load the plugin

### ISSUE THREAD

**Issue by prashants** [maduranga2u/Inventory#1]
Hi,

I have some issues with routes. Check the Webzash/Config/routes.php that I am using.

https://github.com/prashants/webzash/blob/master/Config/routes.php

---

Missing Controller

Error: Webzash.InventoryController could not be found.

Error: Create the class InventoryController below in file: /home/prashants/lampstack/apache2/htdocs/inventory/webzash/app/Plugin/Webzash/Controller/InventoryController.php

<?php
class InventoryController extends WebzashAppController {

}

Notice: If you want to customize this error message, create app/View/Errors/missing_controller.ctp

**Comment by maduranga2u** [comment]
Hi prashants,

i am changed the app/config/bootstrap.php 

CakePlugin::load('Webzash', array('routes' => false, 'bootstrap' => true));

and then add code to app/config/routes.php 

Router::connect('/', array('plugin' => 'webzash', 'controller' => 'dashboard', 'action' => 'index'));

**Comment by prashants** [comment]
works !
